### PR TITLE
Adding CMake and Submodules

### PR DESCRIPTION
**Pull request by phuicy**
1. I have moved your gc and google-tests to git sub-modules
2. I have added CMake build files

I have tested it on two different machines and it all runs.

Thanks,
Guy

### CODE REVIEW

**Comment by crdelozier** [comment]
I've added the changes except for the gc submodule.  The garbage collector used by Ironclad C++ is a modified version of the bdwgc library.

**Comment by phuicy** [comment]
Oh ok. What were the changes?

**Comment by crdelozier** [comment]
The changes are for the use of heap-precise garbage collection with
Ironclad C++.  The main changes are in ironclad/libs/gc/mark.c.  In this
code, we check for a specific allocation tag (GC_DS_PRECISE) and use
"ironclad_precise_mark" to call the allocation's virtual "mark()" method.
This mark() method precisely identifies where the pointers are in the
object.  Overall, heap-precise garbage collection was slightly slower than
fully conservative gc but reduced the amount of memory used by the programs
in a few cases.  More details on the heap-precise garbage collection used
by Ironclad C++ can be found in section 4 of the paper
http://acg.cis.upenn.edu/papers/ironclad-oopsla.pdf.
- Christian

**Comment by phuicy** [comment]
Cool thanks. I have previously read the paper, and really enjoyed it.

**Pull request closed without merging**
